# Curso Numpy

In [2]:
import numpy as np # Foi convensionado usar a biblioteca como np

## Numpy X Listas

### Tamanho fixo

In [3]:
list_a = [1, 2, 3, 4]

In [4]:
type(list_a)

list

In [5]:
print(id(list_a))

124229111344640


In [6]:
list_a.append(5)
print(list_a)
print(id(list_a))

[1, 2, 3, 4, 5]
124229111344640


In [7]:
array_a = np.array([1, 2, 3, 4])

In [8]:
type(array_a)

numpy.ndarray

In [9]:
print(id(array_a))

124228595645392


In [10]:
array_a = np.append(array_a, [5])
print(array_a)
print(id(array_a))

[1 2 3 4 5]
124228595645968


Quando adicionamos um novo elemento na lista convêncional do Python ele permanece o mesmo id, porém quando usamos a biblioteca NumPy podemos perecber como o id muda. Alem do id podemos observar que quando usamos Numpy estamos trabalhando com um objeto ndarray e não uma list.

### Homogêneo

In [11]:
list_a = [1, 2.4, 'a', True, 5]
print(list_a)

[1, 2.4, 'a', True, 5]


In [12]:
type(list_a)

list

In [13]:
for i in list_a:
    # print(i)
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'int'>


In [14]:
array_a = np.array(list_a)
type(array_a)

numpy.ndarray

In [15]:
print(array_a)

['1' '2.4' 'a' 'True' '5']


In [16]:
for i in array_a:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Quando utilizamos a lista do python se preserva os tipos de cada dado, já quando utilizamos o Numpy os tipos de cada elemento é homogeneo.


| Exemplos de dtype | -                 |
|-------------------|-------------------|
| np.int32          | Inteiro de 32 Bits|
| np.complex64      | Numero complexo com 64 Bits|
| object            | Objeto            |

### Vetorização

In [17]:
list_a = [1, 2, 3, 4]
list_b = [5, 6, 7, 8]

list_c = list_a + list_b
print(list_c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [18]:
list_c = []
for i in range(4):
    list_c.append(list_a[i] + list_b[i])

print(list_c)

[6, 8, 10, 12]


In [19]:
array_a = np.array(list_a)
array_b = np.array(list_b)

array_c = array_a + array_b
print(array_c)

[ 6  8 10 12]


In [20]:
array_a - array_b

array([-4, -4, -4, -4])

In [21]:
array_a * array_b

array([ 5, 12, 21, 32])

In [22]:
array_a / array_b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [23]:
array_a % array_b

array([1, 2, 3, 4])

In [24]:
array_a  ** array_b

array([    1,    64,  2187, 65536])

### Broadcasting

In [25]:
list_a = [1, 2, 3, 4]
list_a + 5 # erro

TypeError: can only concatenate list (not "int") to list

In [27]:
list_b = list()
for i in list_a:
    list_b.append(i + 5)

print(list_b)

[6, 7, 8, 9]


In [28]:
array_a = np.array(list_a)
array_a + 5

array([6, 7, 8, 9])

In [30]:
array_b = np.array([[5],[10]])
array_b.shape

(2, 1)

In [31]:
array_a + array_b

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [32]:
array_b = np.array([[5, 6], [10, 11]])

In [34]:
array_a + array_b # erro pois não tem tipos compativeis

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

### EXERCICIOS NÃO RESOLVIDOS

#### Tamanho fixo

Abaixo vamos instanciar um array com 4 elementos.

In [ ]:
array_a = np.array([0, 1, 2, 3])

Utilizando a função `np.append`, adicione o elemento `4` no final deste array. Lembre-se que este elemento deve estar "envelopado" em uma lista: `[4]`. Coloque o resultado em novo array chamado `array_b` e exiba o resultado.

In [ ]:
array_b = ...

In [ ]:
array_b

array([0, 1, 2, 3, 4])

Agora, utilizando a função `id` do Python e o comparador `==`, mostre que os dois arrays têm endereços diferentes na memória, o que mostra que `array_b` é diferente de `array_a`.

💡 Isto ocorre porque, no NumPy, os arrays têm **tamanho fixo**. Se você adicionar elementos no array, um novo array é criado.

In [ ]:
...

False

#### Homogêneo

Instancie um array `array_c` com 3 elementos:
- o número `3` (inteiro)
- o número `7.9` (float)
- o valor `False` (booleano)

Exiba este array.

In [ ]:
array_c = ...

In [ ]:
array_c

array([3. , 7.9, 0. ])

Utilizando um loop `for` para iterar sobre os elementos de `array_c`,  exiba na tela (`print`) o próprio elemento, e o tipo de cada elemento do array, utilizando a função `type`.

In [ ]:
for ...
    print(..., ...)

3.0 <class 'numpy.float64'>
7.9 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>


💡 Observe que, para manter a homogeneidade do array, todos os elementos foram convertidos para o tipo `np.float`.

Agora, utilizando o método `dtype` do array, exiba o tipo de dado que ele armazena.

In [ ]:
...

dtype('float64')

💡 Perceba que o array têm o mesmo tipo de dado que seus elementos.

#### Vetorização

Instancie um array `array_d` com os valores `10`, `11`, `12` e `13`, e um array `array_e` com os valores `1`, `2`, `3` e `4`.

Exiba estes dois arrays.

In [ ]:
array_d = ...
array_e = ...

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

Agora, realize as 4 operações matemáticas básicas (soma, subtração, multiplicação e divisão) utilizando os operadores nativos do Python (`+`, `-`, `*`, `/`). Exiba os resultados diretamente, sem armazená-los em uma variável antes.

In [ ]:
... + ...

array([11, 13, 15, 17])

In [ ]:
...

array([9, 9, 9, 9])

In [ ]:
...

array([10, 22, 36, 52])

In [ ]:
...

array([10.  ,  5.5 ,  4.  ,  3.25])

💡 O uso dos operadores básicos só é possível graças à propriedade vetorial dos arrays do NumPy, que permite operações matemáticas elemento-a-elemento entre arrays.

#### Broadcasting

Vamos reutilizar o `array_d` para demonstrar a propriedade de broadcasting.

Utilize os 4 operadores matemáticos básicos para somar, subtrair, multiplicar e dividir o valor `2` de cada elemento do array.

Printe os resultados diretamente na tela.

In [ ]:
... + 2

array([12, 13, 14, 15])

In [ ]:
...

array([ 8,  9, 10, 11])

In [ ]:
...

array([20, 22, 24, 26])

In [ ]:
...

array([5. , 5.5, 6. , 6.5])

💡 Observe que, se você quiser realizar essas operações em todos os elementos do array com um **valor fixo**, é possível utilizar este valor como um escalar, sem a necessidade de transformá-lo em um array. Isto é possível graças à propriedade de broadcasting.

### EXERCICIOS RESOLVIDOS

#### Tamanho fixo

Abaixo vamos instanciar um array com 4 elementos.

In [38]:
array_a = np.array([0, 1, 2, 3])

Utilizando a função `np.append`, adicione o elemento `4` no final deste array. Lembre-se que este elemento deve estar "envelopado" em uma lista: `[4]`. Coloque o resultado em novo array chamado `array_b` e exiba o resultado.

In [41]:
array_b = np.append(array_a, [4])

In [42]:
array_b

array([0, 1, 2, 3, 4])

Agora, utilizando a função `id` do Python e o comparador `==`, mostre que os dois arrays têm endereços diferentes na memória, o que mostra que `array_b` é diferente de `array_a`.

💡 Isto ocorre porque, no NumPy, os arrays têm **tamanho fixo**. Se você adicionar elementos no array, um novo array é criado.

In [44]:
id(array_a)==id(array_b)

False

#### Homogêneo

Instancie um array `array_c` com 3 elementos:
- o número `3` (inteiro)
- o número `7.9` (float)
- o valor `False` (booleano)

Exiba este array.

In [45]:
array_c = np.array([3, 7.9, False])

In [46]:
array_c

array([3. , 7.9, 0. ])

Utilizando um loop `for` para iterar sobre os elementos de `array_c`,  exiba na tela (`print`) o próprio elemento, e o tipo de cada elemento do array, utilizando a função `type`.

In [47]:
for i in array_c:
    print(i, type(i))

3.0 <class 'numpy.float64'>
7.9 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>


💡 Observe que, para manter a homogeneidade do array, todos os elementos foram convertidos para o tipo `np.float`.

Agora, utilizando o método `dtype` do array, exiba o tipo de dado que ele armazena.

In [49]:
array_c.dtype

dtype('float64')

💡 Perceba que o array têm o mesmo tipo de dado que seus elementos.

#### Vetorização

Instancie um array `array_d` com os valores `10`, `11`, `12` e `13`, e um array `array_e` com os valores `1`, `2`, `3` e `4`.

Exiba estes dois arrays.

In [ ]:
array_d = ...
array_e = ...

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

Agora, realize as 4 operações matemáticas básicas (soma, subtração, multiplicação e divisão) utilizando os operadores nativos do Python (`+`, `-`, `*`, `/`). Exiba os resultados diretamente, sem armazená-los em uma variável antes.

In [ ]:
... + ...

array([11, 13, 15, 17])

In [ ]:
...

array([9, 9, 9, 9])

In [ ]:
...

array([10, 22, 36, 52])

In [ ]:
...

array([10.  ,  5.5 ,  4.  ,  3.25])

💡 O uso dos operadores básicos só é possível graças à propriedade vetorial dos arrays do NumPy, que permite operações matemáticas elemento-a-elemento entre arrays.

#### Broadcasting

Vamos reutilizar o `array_d` para demonstrar a propriedade de broadcasting.

Utilize os 4 operadores matemáticos básicos para somar, subtrair, multiplicar e dividir o valor `2` de cada elemento do array.

Printe os resultados diretamente na tela.

In [ ]:
... + 2

array([12, 13, 14, 15])

In [ ]:
...

array([ 8,  9, 10, 11])

In [ ]:
...

array([20, 22, 24, 26])

In [ ]:
...

array([5. , 5.5, 6. , 6.5])

💡 Observe que, se você quiser realizar essas operações em todos os elementos do array com um **valor fixo**, é possível utilizar este valor como um escalar, sem a necessidade de transformá-lo em um array. Isto é possível graças à propriedade de broadcasting.

## ndarray e atributos