# Curso Numpy

In [1]:
import numpy as np # Foi convensionado usar a biblioteca como np

## Numpy X Listas

### Tamanho fixo

In [85]:
list_a = [1, 2, 3, 4]

In [86]:
type(list_a)

list

In [87]:
print(id(list_a))

124228596279040


In [88]:
list_a.append(5)
print(list_a)
print(id(list_a))

[1, 2, 3, 4, 5]
124228596279040


In [89]:
array_a = np.array([1, 2, 3, 4])

In [90]:
type(array_a)

numpy.ndarray

In [91]:
print(id(array_a))

124228128362192


In [92]:
array_a = np.append(array_a, [5])
print(array_a)
print(id(array_a))

[1 2 3 4 5]
124228128468656


Quando adicionamos um novo elemento na lista convêncional do Python ele permanece o mesmo id, porém quando usamos a biblioteca NumPy podemos perecber como o id muda. Alem do id podemos observar que quando usamos Numpy estamos trabalhando com um objeto ndarray e não uma list.

### Homogêneo

In [93]:
list_a = [1, 2.4, 'a', True, 5]
print(list_a)

[1, 2.4, 'a', True, 5]


In [94]:
type(list_a)

list

In [95]:
for i in list_a:
    # print(i)
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'int'>


In [96]:
array_a = np.array(list_a)
type(array_a)

numpy.ndarray

In [97]:
print(array_a)

['1' '2.4' 'a' 'True' '5']


In [98]:
for i in array_a:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Quando utilizamos a lista do python se preserva os tipos de cada dado, já quando utilizamos o Numpy os tipos de cada elemento é homogeneo.


| Exemplos de dtype | -                 |
|-------------------|-------------------|
| np.int32          | Inteiro de 32 Bits|
| np.complex64      | Numero complexo com 64 Bits|
| object            | Objeto            |

### Vetorização

In [99]:
list_a = [1, 2, 3, 4]
list_b = [5, 6, 7, 8]

list_c = list_a + list_b
print(list_c)

[1, 2, 3, 4, 5, 6, 7, 8]


In [100]:
list_c = []
for i in range(4):
    list_c.append(list_a[i] + list_b[i])

print(list_c)

[6, 8, 10, 12]


In [101]:
array_a = np.array(list_a)
array_b = np.array(list_b)

array_c = array_a + array_b
print(array_c)

[ 6  8 10 12]


In [102]:
array_a - array_b

array([-4, -4, -4, -4])

In [103]:
array_a * array_b

array([ 5, 12, 21, 32])

In [104]:
array_a / array_b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [105]:
array_a % array_b

array([1, 2, 3, 4])

In [106]:
array_a  ** array_b

array([    1,    64,  2187, 65536])

### Broadcasting

In [107]:
list_a = [1, 2, 3, 4]
# lsist_a + 5 # erro

In [108]:
list_b = list()
for i in list_a:
    list_b.append(i + 5)

print(list_b)

[6, 7, 8, 9]


In [109]:
array_a = np.array(list_a)
array_a + 5

array([6, 7, 8, 9])

In [110]:
array_b = np.array([[5],[10]])
array_b.shape

(2, 1)

In [111]:
array_a + array_b

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [112]:
array_b = np.array([[5, 6], [10, 11]])

In [113]:
# array_a + array_b # erro pois não tem tipos compativeis

ValueError: operands could not be broadcast together with shapes (4,) (2,2) 

### EXERCICIOS NÃO RESOLVIDOS

#### Tamanho fixo

Abaixo vamos instanciar um array com 4 elementos.

In [ ]:
array_a = np.array([0, 1, 2, 3])

Utilizando a função `np.append`, adicione o elemento `4` no final deste array. Lembre-se que este elemento deve estar "envelopado" em uma lista: `[4]`. Coloque o resultado em novo array chamado `array_b` e exiba o resultado.

In [ ]:
array_b = ...

In [ ]:
array_b

array([0, 1, 2, 3, 4])

Agora, utilizando a função `id` do Python e o comparador `==`, mostre que os dois arrays têm endereços diferentes na memória, o que mostra que `array_b` é diferente de `array_a`.

💡 Isto ocorre porque, no NumPy, os arrays têm **tamanho fixo**. Se você adicionar elementos no array, um novo array é criado.

In [ ]:
...

False

#### Homogêneo

Instancie um array `array_c` com 3 elementos:
- o número `3` (inteiro)
- o número `7.9` (float)
- o valor `False` (booleano)

Exiba este array.

In [ ]:
array_c = ...

In [ ]:
array_c

array([3. , 7.9, 0. ])

Utilizando um loop `for` para iterar sobre os elementos de `array_c`,  exiba na tela (`print`) o próprio elemento, e o tipo de cada elemento do array, utilizando a função `type`.

In [ ]:
for ...
    print(..., ...)

3.0 <class 'numpy.float64'>
7.9 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>


💡 Observe que, para manter a homogeneidade do array, todos os elementos foram convertidos para o tipo `np.float`.

Agora, utilizando o método `dtype` do array, exiba o tipo de dado que ele armazena.

In [ ]:
...

dtype('float64')

💡 Perceba que o array têm o mesmo tipo de dado que seus elementos.

#### Vetorização

Instancie um array `array_d` com os valores `10`, `11`, `12` e `13`, e um array `array_e` com os valores `1`, `2`, `3` e `4`.

Exiba estes dois arrays.

In [ ]:
array_d = ...
array_e = ...

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

Agora, realize as 4 operações matemáticas básicas (soma, subtração, multiplicação e divisão) utilizando os operadores nativos do Python (`+`, `-`, `*`, `/`). Exiba os resultados diretamente, sem armazená-los em uma variável antes.

In [ ]:
... + ...

array([11, 13, 15, 17])

In [ ]:
...

array([9, 9, 9, 9])

In [ ]:
...

array([10, 22, 36, 52])

In [ ]:
...

array([10.  ,  5.5 ,  4.  ,  3.25])

💡 O uso dos operadores básicos só é possível graças à propriedade vetorial dos arrays do NumPy, que permite operações matemáticas elemento-a-elemento entre arrays.

#### Broadcasting

Vamos reutilizar o `array_d` para demonstrar a propriedade de broadcasting.

Utilize os 4 operadores matemáticos básicos para somar, subtrair, multiplicar e dividir o valor `2` de cada elemento do array.

Printe os resultados diretamente na tela.

In [ ]:
... + 2

array([12, 13, 14, 15])

In [ ]:
...

array([ 8,  9, 10, 11])

In [ ]:
...

array([20, 22, 24, 26])

In [ ]:
...

array([5. , 5.5, 6. , 6.5])

💡 Observe que, se você quiser realizar essas operações em todos os elementos do array com um **valor fixo**, é possível utilizar este valor como um escalar, sem a necessidade de transformá-lo em um array. Isto é possível graças à propriedade de broadcasting.

### EXERCICIOS RESOLVIDOS

#### Tamanho fixo

Abaixo vamos instanciar um array com 4 elementos.

In [ ]:
array_a = np.array([0, 1, 2, 3])

Utilizando a função `np.append`, adicione o elemento `4` no final deste array. Lembre-se que este elemento deve estar "envelopado" em uma lista: `[4]`. Coloque o resultado em novo array chamado `array_b` e exiba o resultado.

In [ ]:
array_b = np.append(array_a, [4])

In [ ]:
array_b

array([0, 1, 2, 3, 4])

Agora, utilizando a função `id` do Python e o comparador `==`, mostre que os dois arrays têm endereços diferentes na memória, o que mostra que `array_b` é diferente de `array_a`.

💡 Isto ocorre porque, no NumPy, os arrays têm **tamanho fixo**. Se você adicionar elementos no array, um novo array é criado.

In [ ]:
id(array_a)==id(array_b)

False

#### Homogêneo

Instancie um array `array_c` com 3 elementos:
- o número `3` (inteiro)
- o número `7.9` (float)
- o valor `False` (booleano)

Exiba este array.

In [ ]:
array_c = np.array([3, 7.9, False])

In [ ]:
array_c

array([3. , 7.9, 0. ])

Utilizando um loop `for` para iterar sobre os elementos de `array_c`,  exiba na tela (`print`) o próprio elemento, e o tipo de cada elemento do array, utilizando a função `type`.

In [ ]:
for i in array_c:
    print(i, type(i))

3.0 <class 'numpy.float64'>
7.9 <class 'numpy.float64'>
0.0 <class 'numpy.float64'>


💡 Observe que, para manter a homogeneidade do array, todos os elementos foram convertidos para o tipo `np.float`.

Agora, utilizando o método `dtype` do array, exiba o tipo de dado que ele armazena.

In [ ]:
array_c.dtype

dtype('float64')

💡 Perceba que o array têm o mesmo tipo de dado que seus elementos.

#### Vetorização

Instancie um array `array_d` com os valores `10`, `11`, `12` e `13`, e um array `array_e` com os valores `1`, `2`, `3` e `4`.

Exiba estes dois arrays.

In [ ]:
array_d = np.array([10, 11, 12, 13])
array_e = np.array([1, 2, 3, 4])

array_d, array_e

(array([10, 11, 12, 13]), array([1, 2, 3, 4]))

Agora, realize as 4 operações matemáticas básicas (soma, subtração, multiplicação e divisão) utilizando os operadores nativos do Python (`+`, `-`, `*`, `/`). Exiba os resultados diretamente, sem armazená-los em uma variável antes.

In [ ]:
array_d + array_e

array([11, 13, 15, 17])

In [ ]:
array_d - array_e

array([9, 9, 9, 9])

In [ ]:
array_d * array_e

array([10, 22, 36, 52])

In [ ]:
array_d / array_e

array([10.  ,  5.5 ,  4.  ,  3.25])

💡 O uso dos operadores básicos só é possível graças à propriedade vetorial dos arrays do NumPy, que permite operações matemáticas elemento-a-elemento entre arrays.

#### Broadcasting

Vamos reutilizar o `array_d` para demonstrar a propriedade de broadcasting.

Utilize os 4 operadores matemáticos básicos para somar, subtrair, multiplicar e dividir o valor `2` de cada elemento do array.

Printe os resultados diretamente na tela.

In [ ]:
array_d + 2

array([12, 13, 14, 15])

In [ ]:
array_d - 2

array([ 8,  9, 10, 11])

In [ ]:
array_d * 2

array([20, 22, 24, 26])

In [ ]:
array_d / 2

array([5. , 5.5, 6. , 6.5])

💡 Observe que, se você quiser realizar essas operações em todos os elementos do array com um **valor fixo**, é possível utilizar este valor como um escalar, sem a necessidade de transformá-lo em um array. Isto é possível graças à propriedade de broadcasting.

## ndarray e atributos

### Array a partir de dados

In [5]:
array_from_list = np.array([1, 2, 3])
array_from_list

array([1, 2, 3])

In [7]:
list_a = [1, 2, 3]
type(list_a)

list

In [9]:
array_from_list = np.array(list_a)
array_from_list

array([1, 2, 3])

In [12]:
type(array_from_list)

numpy.ndarray

In [14]:
tuple_a = (1, 2, 3)
tuple_a, type(tuple_a)

((1, 2, 3), tuple)

In [16]:
array_from_tuple = np.array(tuple_a)
print(array_from_tuple)
print(type(array_from_tuple))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
array_from_list + 5

array([6, 7, 8])

In [18]:
array_from_tuple + 5

array([6, 7, 8])

In [20]:
set_a = {1, 2, 3, 4}
print(set_a)
print(type(set_a))

{1, 2, 3, 4}
<class 'set'>


In [24]:
array_from_set = np.array(set_a)
array_from_set

array({1, 2, 3, 4}, dtype=object)

In [26]:
# array_from_set + 5 # erro

TypeError: unsupported operand type(s) for +: 'set' and 'int'

In [29]:
dict_a = {1 : 'a', 2 : 'b'}
print(dict_a)
print(type(dict_a))

{1: 'a', 2: 'b'}
<class 'dict'>


In [32]:
array_from_dict = np.array(dict_a)
array_from_dict

array({1: 'a', 2: 'b'}, dtype=object)

In [33]:
# array_from_dict + 5

TypeError: unsupported operand type(s) for +: 'dict' and 'int'

### Array de 1 dimensão

In [44]:
array_1d = np.array([1, 2, 3])
array_1d, array_1d[0]

(array([1, 2, 3]), 1)

### Array de 2 dimensões

In [35]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])
array_2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [38]:
# np.array([[1, 2, 3], [4, 5], [7, 8, 9], [10]]) #erro

In [41]:
array_2d[0]

array([1, 2, 3])

In [42]:
array_2d[1][1]

5

### Array de n dimensões

In [45]:
array_3d = np.array([[[1, 2, 3], 
                      [4, 5, 6], 
                      [7, 8, 9], 
                      [10, 11, 12]],
                      
                      [[13, 14, 15], 
                       [16, 17, 18], 
                       [19, 20, 21], 
                       [22, 23, 24]]])

array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [46]:
array_3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
array_3d[0][0]

array([1, 2, 3])

In [49]:
array_3d[0][2][1]

8

### Atributos do array

#### `size`

In [50]:
array_from_list

array([1, 2, 3])

In [51]:
array_from_list.size

3

In [52]:
array_2d.size

12

In [53]:
array_3d.size

24

#### `ndim`

In [54]:
array_from_list.ndim

1

In [55]:
array_2d.ndim

2

In [56]:
array_3d.ndim

3

#### `shape`

In [57]:
array_from_list.shape

(3,)

In [58]:
array_2d.shape

(4, 3)

In [60]:
array_3d.shape

(2, 4, 3)

#### `itemsize`

In [62]:
array_from_list.itemsize

8

In [63]:
array_2d.itemsize

8

In [64]:
array_3d.itemsize

8

#### `nbytes`

In [66]:
array_from_list.nbytes

24

In [67]:
array_2d.nbytes

96

In [68]:
array_3d.nbytes

192

#### `dtype`

In [69]:
array_from_list.dtype

dtype('int64')

In [71]:
array_2d.dtype

dtype('int64')

In [72]:
array_3d.dtype

dtype('int64')

In [74]:
array_32bits = np.array([1, 2, 3], dtype = np.int32)
array_32bits

array([1, 2, 3], dtype=int32)

In [75]:
np.array([1, 2, 3], dtype=np.float32)

array([1., 2., 3.], dtype=float32)

In [76]:
np.array([1, 2, 3], dtype=np.str_)

array(['1', '2', '3'], dtype='<U1')

### Exercicios Resolvidos

#### Array de 1 dimensão

Instancie um `array_a` com os elementos `1`, `2`, `3`, `4` e `5`, em uma única dimensão.

Printe dois atributos deste array, `shape` e `ndim`, para confirmar que este é um array 1-D.

In [ ]:
array_a = np.array([1, 2, 3, 4, 5])

In [ ]:
array_a.shape, array_a.ndim

((5,), 1)

Printe também o atributo `size` para verificar quantos elementos este array contém.

In [ ]:
array_a.size

5

#### Array de 2 dimensões

Agora instancie um `array_b` com os elementos `1` a `10`, organizados em 2 linhas e 5 colunas. Lembre-se que, neste caso, você precisa representar os valores no formato **lista de listas**, onde cada lista interna representa uma linha do array.

Também printe `shape`, `ndim` e `size`.

In [ ]:
array_b = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10]])

In [ ]:
array_b.shape, array_b.ndim, array_b.size

((2, 5), 2, 10)

#### Array de 3 dimensões

Crie um `array_c` com os elementos `1` a `20`, com profundidade 2, 5 linhas e 2 colunas. Aqui, você vai precisar representar os valores no formato **lista de listas de listas**.

Printe `shape`, `ndim` e `size`.

In [ ]:
array_c = np.array([[[ 1,  2],
                     [ 3,  4],
                     [ 5,  6],
                     [ 7,  8],
                     [ 9, 10]],

                     [[11, 12],
                      [13, 14],
                      [15, 16],
                      [17, 18],
                      [19, 20]]])

In [ ]:
array_c.shape, array_c.ndim, array_c.size

((2, 5, 2), 3, 20)

#### `dtype`

Agora vamos verificar como você pode instanciar um array explicitando o tipo de dado que será armazenado.

Abaixo você recebe uma lista, `list_d`, com 5 valores informados como inteiros.

In [ ]:
list_d = [1, 2, 3, 4, 5]
for i in list_d:
    print(i, type(i))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
5 <class 'int'>


Partindo desta lista, instancie um array `array_d` convertendo seu `dtype` para `np.float16`.

Exiba o `dtype` deste array.

In [ ]:
array_d = np.array(list_d, dtype=np.float16)

In [ ]:
array_d.dtype

dtype('float16')

Agora instancie o mesmo `array_d` mas com `dtype` igual a `np.float32`. Exiba o `dtype`.

In [ ]:
array_d = np.array(list_d, dtype=np.float32)

In [ ]:
array_d.dtype

dtype('float32')

Novamente instancie `array_d`, mas agora com `dtype` igual a `np.str_`. Exiba o `dtype`.

In [ ]:
array_d = np.array(list_d, dtype=np.str_)

In [ ]:
array_d.dtype

dtype('<U1')

Por último instancie `array_d` com `dtype` igual a `np.bool`.

Desta vez, exiba o próprio array e seu `dtype`.

In [ ]:
array_d = np.array(list_d, dtype=np.bool_)

In [ ]:
array_d

array([ True,  True,  True,  True,  True])

In [ ]:
array_d.dtype

dtype('bool')

💡 Observe que todos os valores são expressos como `True`. Isto ocorre porque, para números, o Python interpreta `0` como `False`, e qualquer outro valor como `True`.