In [7]:
import numpy as np

# Bubble Sort

In [2]:
def bubble_sort(vetor):
    n = len(vetor)

    for i in range(n):
        for j in range(0, n-i-1):
            if vetor [j] > vetor[j+1]:
                temp = vetor[j]
                vetor[j] = vetor[j+1]
                vetor[j+1] = temp
    return vetor


## Tests

In [9]:
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [5]:
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Selection Sort

In [12]:
def selection_sort(vetor):
    n = len(vetor)
    for i in range(n):
        id_min = i
        for j in range(1+i, n):
            if vetor[j] < vetor[id_min]:
                id_min = j
            
        temp = vetor[i]
        vetor[i] = vetor[id_min]
        vetor[id_min] = temp
    
    return vetor
            

In [ ]:
selection_sort(np.array([15, 34, 8, 3]))

In [ ]:
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

# Insertion Sort

In [19]:
def insertion_sort(vetor):
    n = len(vetor)

    for i in range(1, n):
        marked = vetor[i]
        j = i-1

        while j >= 0 and marked < vetor[j]:
            vetor[j+1] = vetor[j]
            j -= 1
        
        vetor[j+1] = marked
    
    return vetor


In [20]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [21]:
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Shell Sort

In [23]:
def shell_sort(vetor):
    intervalo = len(vetor) // 2

    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j-intervalo]
                j -= intervalo
            vetor[j]=temp
        
        intervalo //= 2

    return vetor

In [24]:
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [25]:
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])