In [21]:
import numpy as np

# Bubble Sort

In [22]:
def bubble_sort(vetor):
    n = len(vetor)

    for i in range(n):
        for j in range(0, n-i-1):
            if vetor [j] > vetor[j+1]:
                temp = vetor[j]
                vetor[j] = vetor[j+1]
                vetor[j+1] = temp
    return vetor


## Tests

In [23]:
bubble_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [24]:
bubble_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Selection Sort

In [25]:
def selection_sort(vetor):
    n = len(vetor)
    for i in range(n):
        id_min = i
        for j in range(1+i, n):
            if vetor[j] < vetor[id_min]:
                id_min = j
            
        temp = vetor[i]
        vetor[i] = vetor[id_min]
        vetor[id_min] = temp
    
    return vetor
            

In [26]:
selection_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [27]:
selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Insertion Sort

In [28]:
def insertion_sort(vetor):
    n = len(vetor)

    for i in range(1, n):
        marked = vetor[i]
        j = i-1

        while j >= 0 and marked < vetor[j]:
            vetor[j+1] = vetor[j]
            j -= 1
        
        vetor[j+1] = marked
    
    return vetor


In [29]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [30]:
insertion_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Shell Sort

In [31]:
def shell_sort(vetor):
    intervalo = len(vetor) // 2

    while intervalo > 0:
        for i in range(intervalo, len(vetor)):
            temp = vetor[i]
            j = i
            while j >= intervalo and vetor[j - intervalo] > temp:
                vetor[j] = vetor[j-intervalo]
                j -= intervalo
            vetor[j]=temp
        
        intervalo //= 2

    return vetor

In [32]:
shell_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [33]:
shell_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Merge Sort

In [34]:
def merge_sort(vetor):
    if len(vetor) > 1:
        div = len(vetor) // 2
        left = vetor[:div].copy()
        right = vetor[div:].copy()

        merge_sort(left)
        merge_sort(right)

        # sort left and right
        i = j = k = 0
        while i < len(left) and j < len(right):
            if left[i] < right[j]:
                vetor[k] = left[i]
                i += 1
            else:
                vetor[k] = right[j]
                j += 1
            k += 1
            
        #final sort
        while i < len(left):
            vetor[k] = left[i]
            i += 1
            k += 1
        while j < len(right):
            vetor[k] = right[j]
            j += 1
            k += 1
    return vetor

In [35]:
merge_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

In [36]:
merge_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Quick Sort

In [37]:
def particion(vetor, begin, end):
    pivot = vetor[end]
    i = begin - 1

    for j in range(begin, end):
        if vetor[j] <= pivot:
            i += 1
            vetor[i], vetor[j] = vetor[j], vetor[i]
    vetor[i+1], vetor[end] = vetor[end], vetor[i+1]

    return i+1

In [38]:
def quick_sort(vetor, begin, end):
    if begin < end:
        position = particion(vetor, begin, end)

        #left sort
        quick_sort(vetor,begin, position-1)
        #right sort
        quick_sort(vetor, position+1, end)

    return vetor

    

In [39]:
vetor = np.array([15, 34, 8, 3])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 3,  8, 15, 34])

In [40]:
vetor = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
quick_sort(vetor, 0, len(vetor) - 1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Exercises

In [65]:
vetor = np.random.rand(5000)

## Exercise 1 - Sorting unsorted vector

In [66]:
%timeit bubble_sort(vetor.copy())

5.11 s ± 211 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [67]:
%timeit selection_sort(vetor.copy())

2.82 s ± 136 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [68]:
%timeit insertion_sort(vetor.copy())

2.57 s ± 227 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [69]:
%timeit shell_sort(vetor.copy())

45.5 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [70]:
%timeit merge_sort(vetor.copy())

36.9 ms ± 897 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [71]:
%timeit quick_sort(vetor.copy(), 0, 4999)

29.6 ms ± 5.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Exercise 2 - Sorted Vector vs Sorting a Unsorted Vector

In [72]:
class VetorOrdenado:
    def __init__(self, capacity):
        self.capacity = capacity
        self.last_position = -1
        self.values = np.empty(self.capacity, dtype=float)
    
    # O(n)
    def print_values(self):
        if self.last_position == -1:
            print('The vector is empty')
        else:
            for i in range(self.last_position+1):
                print(i, '-', self.values[i])

    # O(n)
    def insert_value(self, value):
        if self.last_position == self.capacity-1:
            print("Max capacity reached")
            return

        position = 0
        
        for i in range(self.last_position+1):
            position = i
            if self.values[i] > value:
                break
            if i == self.last_position:
                position +=1

        for i in range(self.last_position, position-1, -1):
            self.values[i+1] = self.values[i]

#        x = self.last_position
#        while x >= position:
#            self.values[x+1] = self.values[x]
#            x -= 1

        self.values[position] = value
        self.last_position += 1
    
    def linear_search_value(self, value):

        i = 0
        while self.values[i] <= value or i == self.last_position:
            if self.values[i] == value:
                return i
            i += 1
        return -1

        # for i in range(self.last_position+1):
        #     if self.values[i] == value:
        #         return i
        #     if self.values[i] > value:
        #         return -1

    # O(log n)
    def binary_search_value(self, value):
        lower_limit = 0
        upper_limit = self.last_position

        while True:
            atual_position = int((upper_limit + lower_limit)/2)
            if self.values[atual_position] == value:
                return atual_position  
            elif lower_limit > upper_limit:
                return -1          
            elif self.values[atual_position] < value:
                lower_limit = atual_position+1
            else:
                upper_limit = atual_position - 1

        
    def exclude_value(self, value):
        position = self.search_value(value)
        if position == -1:
            print("This value wasn't in the vector")
            return -1
        
        for i in range(position, self.last_position+1):
            self.values[i] = self.values[i+1]
        self.last_position -= 1

In [73]:
def vector_intert(values):
    vetor = VetorOrdenado(len(values))
    for i in values:
        vetor.insert_value(i)

In [74]:
%timeit vector_intert(vetor.copy())

2.38 s ± 69.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
